import { DefaultTheme } from "react-native-paper";
export const COLORS = {
  primary: '#1B5E20', 
  primaryLight: '#4CAF50',
  primaryDark: '#0D4E14',
  secondary: '#FF9800', 
  secondaryLight: '#FFB74D',
  secondaryDark: '#F57C00',
  accent: '#FFD700', 
  accentLight: '#FFF176',
  accentDark: '#FBC02D',
  success: '#4CAF50',
  warning: '#FF9800',
  error: '#F44336',
  info: '#2196F3',
  white: '#FFFFFF',
  black: '#000000',
  gray: '#757575',
  lightGray: '#BDBDBD',
  darkGray: '#424242',
  background: '#F5F5F5',
  surface: '#FFFFFF',
  lightGreen: '#E8F5E8',
  lightOrange: '#FFF3E0',
  lightBlue: '#E3F2FD',
  textPrimary: '#212121',
  textSecondary: '#757575',
  textHint: '#BDBDBD',
  textInverse: '#FFFFFF',
};
export const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: COLORS.primary,
    accent: COLORS.secondary,
    background: COLORS.background,
    surface: COLORS.surface,
    text: COLORS.textPrimary,
  },
};